### ISSUE TITLE
Project state

### ISSUE THREAD

**Issue by ltoshev** [Ks89/angular-cli-skeleton#24]
Hi Stefano,

what is the project state, can it be used for a real world project or I should wait? Do you need any help on this one. I am not really good at making angular build tools, but I am good at development as whole and can learn.

Kind Regards,
Lyubomir

**Comment by Ks89** [comment]
Hi. I used this project for a real application already in production (but without ssr) for a big company. And it's working, because it's based on best practices and so on.

Now I'm working on another real application (always without ssr). 

So the answer is yes. You can use it like me 😀 without problems. 

However I have some questions: 
- do you need server side rendering? 
- do you need app shell
- do you need service workers
- do you need web sockets 

Any help is well accepted. For instance I have to work on ssr, sockets with ssr enabled, internationalization and so on. 
Also documentation is really important, so yes if you wanna help this will be accepted for sure. If you want we can tank about what to add and when.

**Comment by ltoshev** [comment]
Hi

on your questions, I need none of those. 

I need internationalization. SSR seems interesting for future, how does that work?

**Comment by Ks89** [comment]
SSR today is practically unusable (in real applications)  and I'm not sure if it will be useful in the future, because SEO will be always better.

International is useful also for me and I have to add it in next releases after authentication with jwt. So if you want to help me experimenting on I18n with angular-cli feel free to create pull requests. I'll help to add it into the project.

**Comment by Ks89** [comment]
I thought that probably is better to add I18n before than authentication. If you want to help feel free to contribute.

**Comment by Ks89** [comment]
I used I18n in another project, but angular team decided to add also runtime translation in Angular 6.the problem is that it will be experimental.
For this reason I prefer to wait a little bit to understand the right direction. If someone need I18n, it's very simple to add it following official tutorial

**Comment by Ks89** [comment]
close because inactive
